import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Silebar from "../components/Silebar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Whatsapp 3.0</title>
        <meta name="description" content="Generated by Bio dev" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Silebar />
    </>
  );
}
